### ISSUE TITLE
Error while running create_title_file_from_manifest with a relative paths for multiple lanes. 

### ISSUE THREAD

**Issue by maysunh** [mskcc/ACCESS-Pipeline#12]
Small issue: 
When trying to create multiple title-files from one manifest, relative paths (i.e. ../../DIR/Manifest) caused the system to error out. It would be great if you could get the program to accept relative paths, if not, could you try to catch this error. (This is not an issue if there is only 1 lane).

Example of error below: 

create_title_file_from_manifest -i ../metadata/Proj_05500_FC_sample_manifest.xlsx -o ../metadata/5500-FC-title-file.txt

Traceback (most recent call last):
  File "/home/hasanm/access_pipeline_0.0.32/bin/create_title_file_from_manifest", line 11, in <module>
    load_entry_point('access-pipeline==0.0.32', 'console_scripts', 'create_title_file_from_manifest')()
  File "/home/hasanm/access_pipeline_0.0.32/lib/python2.7/site-packages/access_pipeline-0.0.32-py2.7.egg/python_tools/pipeline_kickoff/create_title_file_from_manifest.py", line 75, in main
    create_title_file(args.manifest_file_path, args.output_filename)
  File "/home/hasanm/access_pipeline_0.0.32/lib/python2.7/site-packages/access_pipeline-0.0.32-py2.7.egg/python_tools/pipeline_kickoff/create_title_file_from_manifest.py", line 61, in create_title_file
    title_file_sub.to_csv('lane-{}_'.format(lane) + output_filename, sep='\t', index=False)
  File "/home/hasanm/access_pipeline_0.0.32/lib/python2.7/site-packages/pandas-0.19.0-py2.7-linux-x86_64.egg/pandas/core/frame.py", line 1381, in to_csv
    formatter.save()
  File "/home/hasanm/access_pipeline_0.0.32/lib/python2.7/site-packages/pandas-0.19.0-py2.7-linux-x86_64.egg/pandas/formats/format.py", line 1460, in save
    compression=self.compression)
  File "/home/hasanm/access_pipeline_0.0.32/lib/python2.7/site-packages/pandas-0.19.0-py2.7-linux-x86_64.egg/pandas/io/common.py", line 334, in _get_handle
    f = open(path, mode)
IOError: [Errno 2] No such file or directory: 'lane-1_../metadata/5500-FC-title-file.txt'

**Comment by ionox0** [comment]
@maysunh fixed!
